# Generated by Django 2.0.1 on 2018-04-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('type', models.IntegerField(verbose_name=((0, 'Normal'), (1, 'Stair'), (3, 'Elevator'), (4, 'Train')))),
            ],
            options={
                'db_table': 'Neighbor',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('type', models.IntegerField(verbose_name=((0, 'Joint'), (2, 'Gate'), (3, 'Counter'), (4, 'Food'), (5, 'Retail'), (7, 'Club')))),
                ('floor', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Node',
            },
        ),
        migrations.AddField(
            model_name='neighbor',
            name='from_node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node_id', to='nav.Node'),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='to_node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node_id', to='nav.Node'),
        ),
    ]
