# Generated by Django 2.0.1 on 2018-04-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='from_node_id',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='to_node_id',
        ),
        migrations.AddField(
            model_name='neighbor',
            name='from_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='nav.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbor',
            name='to_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='nav.Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='type',
            field=models.IntegerField(verbose_name=((0, 'Normal'), (1, 'Stair'), (3, 'Elevator'), (4, 'Train'), (9, 'Security'))),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.IntegerField(verbose_name=((0, 'Joint'), (1, 'Security'), (2, 'Gate'), (3, 'Counter'), (4, 'Food'), (5, 'Retail'), (7, 'Club'), (9, 'Exit'))),
        ),
    ]
