# Generated by Django 2.0.2 on 2018-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
