# Generated by Django 2.0.2 on 2018-02-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_node_node_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_id',
        ),
    ]
